### ISSUE TITLE
change twitter link to a list of Neontribe person accounts - so we have more tweets

### ISSUE THREAD

**Issue by katjam** [neontribe/neontribe-ghost#1]
@harryharrold 
Please set up a list in the neontribe twitter account called neontribe including all Neontribe employees (or the one's you want anyway)...

Then @Mottokrosh  - 
Link the footer twitter icon to: https://twitter.com/neontribe/lists/neontribe

**Comment by harryharrold** [comment]
Done!

https://twitter.com/neontribe/lists/the-neontribe is the url....
